#!/usr/local/bin/escript

%% -*- erlang -*-
%%! -smp enable -sname start_life

main([WorldFile]) ->
  InitialWorld = parser:parse_world(WorldFile),
  life:evolve(5,InitialWorld, fun(World) -> printer:print_world(World) end);

main(_) ->
  io:format("usage: life <initial world file>\n", []).
